services:
  # Entrypoint for external users
  ingress:
    container_name: "traefik"
    image: "traefik:v3.4"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80" # Available at http://localhost
      - "8080:8080" # Admin UI. Available at http://localhost:8080
    volumes:
      # - "/var/run/docker.sock:/var/run/docker.sock:ro" # Linux
      - "//var/run/docker.sock:/var/run/docker.sock:ro" # Windows

  # Our own service
  example-service:
    image: ghcr.io/pacolomoreno/2025-06-gitops-soa/example-service:b07f603dae5407b9faf3a79a862458425fdcf101
    environment:
      DATABASE_CONNECTIONSTRING: "postgresql://myuser:mypassword@localhost:5432/mydatabase"
    # Traefik supports dynamic configuration through labeling containers (you can do static and embed the same in a config file)
    # Reference the Traefik docs for options: https://doc.traefik.io/traefik/
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.example-service.entrypoints=web" # For the entrypoint web
      - "traefik.http.routers.example-service.rule=PathPrefix(`/api/example`)" # Forward /api/example
      # Strip the prefix, so the service is unaware
      - "traefik.http.middlewares.example-service.stripprefix.prefixes=/api/example"
      - "traefik.http.routers.example-service.middlewares=example-service"
      # Forward to port 8080 on the service container
      - "traefik.http.services.example-service.loadbalancer.server.port=8080"


  podinfo:
    image: ghcr.io/stefanprodan/podinfo
    
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.podinfo.entrypoints=web" # For the entrypoint web
      - "traefik.http.routers.podinfo.rule=PathPrefix(`/api/podinfo`)" # Forward /api/podinfo
      # Strip the prefix, so the service is unaware
      - "traefik.http.middlewares.podinfo.stripprefix.prefixes=/api/podinfo"
      - "traefik.http.routers.podinfo.middlewares=podinfo"
      # Forward to port 9898 on the service container
      - "traefik.http.services.podinfo.loadbalancer.server.port=9898"