name: continuous-delivery

# Runs this workflow on
on:
  # Manual, or external, triggering of workflow
  workflow_dispatch:
  # And pushes/commits to
  push:
    # These branches
    branches:
      - main
    # And only if changes are in thes paths
    paths:
      - services/**

# Grant permission for the worker to read the repository
permissions:
  contents: read

# Variables available to the builder
env:
  IMAGE_NAME_PREFIX: pacolomoreno/2025-06-gitops-soa

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      packages: write # needed for GitHub Container Registry (ghcr) access

    # Run the step once for each of the entries in the matrix
    strategy:
      matrix:
        # The name of all the service containers we want to push
        service:
          - example-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.IMAGE_NAME_PREFIX }}/${{ matrix.service }}:latest
            ghcr.io/${{ env.IMAGE_NAME_PREFIX }}/${{ matrix.service }}:${{ github.sha }}
